POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Learning Functional Programming with Scala",
  "author": "Ryan Susana",
  "url": "https://ryansusana.medium.com/learning-functional-programming-with-scala-ccc7bf68214f",
  "likes": 99  
}


###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Why use Scala for building backend applications?",
  "author": "JAROSLAV REGEC",
  "url": "https://scalac.io/blog/why-use-scala/",
  "likes": 1 
}
